# TODO: Experimental feature
name: 'CD/Container'
on:
    workflow_dispatch:
    push:
        branches: ['stable']

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

permissions:
  contents: read

jobs:
    build:
        name: 'Build container image'
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        env:
            IMAGE_REGISTRY: 'ghcr.io/${{ github.repository_owner }}'
            IMAGE_NAME: 'frontend'
            IMAGE_TAG: 'experimental ${{ github.sha }}'

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
              with:
                egress-policy: audit

            - name: 'Checkout'
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: 'Build image'
              id: build_image
              uses: redhat-actions/buildah-build@b4dc19b4ba891854660ab1f88a097d45aa158f76 # v2.12
              with:
                  containerfiles: ./Containerfile
                  image: ${{ env.IMAGE_NAME }}
                  tags: ${{ env.IMAGE_TAG }}
                  oci: false

            - name: 'Lowercase registry'
              id: registry_case
              uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
              with:
                  string: ${{ env.IMAGE_REGISTRY }}

            - name: 'Push to GHCR'
              uses: redhat-actions/push-to-registry@9986a6552bc4571882a4a67e016b17361412b4df # v2.7.1
              env:
                  REGISTRY_USER: ${{ github.actor }}
                  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

              with:
                  image: ${{ steps.build_image.outputs.image }}
                  tags: ${{ steps.build_image.outputs.tags }}
                  registry: ${{ steps.registry_case.outputs.lowercase }}
                  username: ${{ env.REGISTRY_USER }}
                  password: ${{ env.REGISTRY_PASSWORD }}
                  extra-args: |
                      --disable-content-trust
